name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MONGODB_DB_NAME: mongodb
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: 'cluster0.yljp0vj.mongodb.net'
      MONGODB_USERNAME: gusaindb
      MONGODB_PASSWORD: FnPuQtcuBbdxyibV
      PORT: 3000
     


    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
       
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm i
      - name: Run Server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }}"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: OUtput information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
          